definitions:
  models.SimpleMessage:
    properties:
      data:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /simple-messages:
    post:
      consumes:
      - application/json
      description: Send message to simple Kafka topic
      parameters:
      - description: Message payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SimpleMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send simple message
      tags:
      - messages
swagger: "2.0"
